# docker-compose.yml

version: '3.8'

services:
  web:
    build: ./front_end
    command: http-server dist -p 80
    ports: 
      - 80:80
    depends_on: 
      - api
  api:
    build: ./fast_app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000'
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=db

volumes:
  postgres_data:
