version: "3"

services:
    postgres:
        image: postgres:latest
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_DB=db

    api:
        build: . 
        ports:
            - "8000:8000"
        depends_on: 
            - postgres