# docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn fast_app.main:app --host 0.0.0.0 --port 8000'
    #volumes:
    #  - .:/fast_app
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=db

volumes:
  postgres_data:
