apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - args:
            - bash
            - -c
            - while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000
          env:
            - name: SQLALCHEMY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: database_url
          image: <link to api image on gitlab>
          name: api
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
