# Web Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: todo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - args:
            - http-server
            - dist
            - -p
            - "7272"
          image: <link to web image on gitlab>
          name: todo-web
          ports:
            - containerPort: 7272
          resources: {}
      restartPolicy: Always
status: {}
---
# Web Service, publically exposes port 31000
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  ports:
    - name: "7272"
      port: 7272
      targetPort: 7272
      nodePort: 31000
  selector:
    app: todo-web
  type: LoadBalancer
---
# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - args:
            - bash
            - -c
            - while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000
          env:
            - name: SQLALCHEMY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: database_url
          image: <link to api image on gitlab>
          name: api
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
---
# API service
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
# Database deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: todo-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgress_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgress_username
          image: postgres:13-alpine
          name: todo-postgres
          ports:
            - containerPort: 5432
---
# Database Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: todo-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

