apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: todo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - args:
            - http-server
            - dist
            - -p
            - "7272"
          image: <link to web image on gitlab>
          name: todo-web
          ports:
            - containerPort: 7272
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  ports:
    - name: "7272"
      port: 7272
      targetPort: 7272
      nodePort: 31000
  selector:
    app: todo-web
  type: LoadBalander